"""Static skill inventory used for baseline matching."""

SKILL_DATABASE = [
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "next.js",
    "node.js",
    "express",
    "fastapi",
    "django",
    "flask",
    "mongodb",
    "postgresql",
    "mysql",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "git",
    "ci/cd",
    "terraform",
    "linux",
    "html",
    "css",
    "tailwind css",
    "rest api",
    "graphql",
    "machine learning",
    "deep learning",
    "nlp",
    "pandas",
    "numpy",
    "scikit-learn",
    "pytorch",
    "tensorflow",
    "data analysis",
    "power bi",
    "tableau",
    "agile",
    "scrum",
    "system design",
    "microservices",
    "unit testing",
    "pytest",
]
